// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package com.oglib.spirit.boot.collect.experience.model;

public interface FrameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Frame)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messageName = 1;</code>
   * @return The messageName.
   */
  String getMessageName();
  /**
   * <code>string messageName = 1;</code>
   * @return The bytes for messageName.
   */
  com.google.protobuf.ByteString
      getMessageNameBytes();

  /**
   * <code>bytes data = 2;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();
}
