// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package com.oglib.spirit.boot.collect.experience.model;

public interface OrgEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:OrgEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string orgName = 1;</code>
   * @return The orgName.
   */
  String getOrgName();
  /**
   * <code>string orgName = 1;</code>
   * @return The bytes for orgName.
   */
  com.google.protobuf.ByteString
      getOrgNameBytes();

  /**
   * <code>string orgNo = 2;</code>
   * @return The orgNo.
   */
  String getOrgNo();
  /**
   * <code>string orgNo = 2;</code>
   * @return The bytes for orgNo.
   */
  com.google.protobuf.ByteString
      getOrgNoBytes();
}
