// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: frame.proto

package com.oglib.spirit.boot.collect.experience.model;

public interface UserEntityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserEntity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>int32 sex = 3;</code>
   * @return The sex.
   */
  int getSex();
}
